version: "3.2"
services:
  api:
    image: flask_api
    container_name: shot_type_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model
    volumes:
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads

  redis:
    image: redis:6.2.6

  model:
    image: shot_type_service
    build:
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./uploads:/src/uploads
